server:
  port: 9090
management:
  endpoint.gateway.enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: AuthFilter


  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  application:
    name: fast-food-gateway

